# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
before_install:
  - Rscript -e 'devtools::install_github("vivianephilipps/marqLevAlgParallel")'
sudo: false
cache: packages
