# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Loglik <- function(K, nD, mapping, paraOpt, paraFixe, posfix, m_is, Mod_MatrixY, Mod_MatrixYprim, df, x, z, q, nb_paraD, x0, z0, q0, if_link, tau, tau_is, modA_mat, DeltaT) {
    .Call('_CInLPN_Loglik', PACKAGE = 'CInLPN', K, nD, mapping, paraOpt, paraFixe, posfix, m_is, Mod_MatrixY, Mod_MatrixYprim, df, x, z, q, nb_paraD, x0, z0, q0, if_link, tau, tau_is, modA_mat, DeltaT)
}

autocorr <- function(K, paraOpt, paraFixe, posfix, ncol_x, ncol_x0, zi, q, nb_paraD, z0i, q0, tau, modA_mat_i, DeltaT) {
    .Call('_CInLPN_autocorr', PACKAGE = 'CInLPN', K, paraOpt, paraFixe, posfix, ncol_x, ncol_x0, zi, q, nb_paraD, z0i, q0, tau, modA_mat_i, DeltaT)
}

pred <- function(K, nD, mapping, paras, m_is, Mod_MatrixY, df, x, z, q, nb_paraD, x0, z0, q0, if_link, tau, tau_is, modA_mat, DeltaT, MCnr, minY, maxY, knots, degree, epsPred) {
    .Call('_CInLPN_pred', PACKAGE = 'CInLPN', K, nD, mapping, paras, m_is, Mod_MatrixY, df, x, z, q, nb_paraD, x0, z0, q0, if_link, tau, tau_is, modA_mat, DeltaT, MCnr, minY, maxY, knots, degree, epsPred)
}

vectorise <- function(M) {
    .Call('_CInLPN_vectorise', PACKAGE = 'CInLPN', M)
}

KmatDiag <- function(Kvector) {
    .Call('_CInLPN_KmatDiag', PACKAGE = 'CInLPN', Kvector)
}

DparChol <- function(q, qvector) {
    .Call('_CInLPN_DparChol', PACKAGE = 'CInLPN', q, qvector)
}

vecaijt <- function(K, t, vec_alpha_ij, modA_mat) {
    .Call('_CInLPN_vecaijt', PACKAGE = 'CInLPN', K, t, vec_alpha_ij, modA_mat)
}

ConstrA <- function(K, t, DeltaT, vec_alpha_ij, modA_mat) {
    .Call('_CInLPN_ConstrA', PACKAGE = 'CInLPN', K, t, DeltaT, vec_alpha_ij, modA_mat)
}

GmatA0totaui <- function(K, vec_alpha_ij, tau_i, DeltaT, modA_mat) {
    .Call('_CInLPN_GmatA0totaui', PACKAGE = 'CInLPN', K, vec_alpha_ij, tau_i, DeltaT, modA_mat)
}

ProdA <- function(K, t2, t1, DeltaT, vec_alpha_ij, modA_mat) {
    .Call('_CInLPN_ProdA', PACKAGE = 'CInLPN', K, t2, t1, DeltaT, vec_alpha_ij, modA_mat)
}

GmatprodAstotau <- function(K, vec_alpha_ij, tau, t_ini, DeltaT, modA_mat) {
    .Call('_CInLPN_GmatprodAstotau', PACKAGE = 'CInLPN', K, vec_alpha_ij, tau, t_ini, DeltaT, modA_mat)
}

tsGmatprodA0totau <- function(K, vec_alpha_ij, tau, DeltaT, modA_mat) {
    .Call('_CInLPN_tsGmatprodA0totau', PACKAGE = 'CInLPN', K, vec_alpha_ij, tau, DeltaT, modA_mat)
}

compoYiNA <- function(Yi) {
    .Call('_CInLPN_compoYiNA', PACKAGE = 'CInLPN', Yi)
}

YiwoNA <- function(Yi) {
    .Call('_CInLPN_YiwoNA', PACKAGE = 'CInLPN', Yi)
}

matNui <- function(nD, tau_i, DeltaT, x0i, alpha_mu0, xi, alpha_mu, G_mat_A_0_to_tau_i) {
    .Call('_CInLPN_matNui', PACKAGE = 'CInLPN', nD, tau_i, DeltaT, x0i, alpha_mu0, xi, alpha_mu, G_mat_A_0_to_tau_i)
}

f_Yi_r_NA_by0 <- function(Yi) {
    .Call('_CInLPN_f_Yi_r_NA_by0', PACKAGE = 'CInLPN', Yi)
}

YiNui <- function(nD, matrixP, tau, tau_i, DeltaT, Yi, x0i, alpha_mu0, xi, alpha_mu, G_mat_A_0_to_tau_i) {
    .Call('_CInLPN_YiNui', PACKAGE = 'CInLPN', nD, matrixP, tau, tau_i, DeltaT, Yi, x0i, alpha_mu0, xi, alpha_mu, G_mat_A_0_to_tau_i)
}

VecToMat <- function(y, K, m_i) {
    .Call('_CInLPN_VecToMat', PACKAGE = 'CInLPN', y, K, m_i)
}

